Reduce the number of experiments:
1. Run pred_len=96 with all the window_lengths BUT run only the best window_length of the 96 for other pred_lens
2. Run pred_len=96 with all the constructors BUT run only the best 50% (maybe only the best) constructors of the 96 for other pred_lens

Defensive experiments:
1. Pconstructor noise/random as benchmarks
2. Run MLP, LSTM and CNN with other framework
3. CATS: should we modify/shape the exogenous features or add them to the input?

Lacks:

- Feature ablation experiments for the FARM paper
- Experiments for the shaping paper with predicition lengths greater than 96

In [1]:
import os
import pyperclip
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"
from results_utils import get_results, plot_results, get_best_results, get_forecast_plot, shape_best_result_for_final_format

In [2]:
all_results = get_results(with_calc_improv=False)
all_results

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.026185,0.001267,0.035594,0.617929,1.814222,long_term_forecast_ETTh1_96_96Weather_w1251_ip...,iTransformer,96,96,1251,ipmutual,Weather
0,0.026345,0.001277,0.035741,0.629864,1.962374,long_term_forecast_96_96Weather_w1501_iprollco...,PatchTST,96,96,1501,iprollcorr.csv,Weather
0,0.026596,0.001290,0.035922,0.629982,1.933035,long_term_forecast_96_96Weather_w1251_iprollco...,PatchTST,96,96,1251,iprollcorr.csv,Weather
0,0.026508,0.001297,0.036018,0.639845,2.016285,long_term_forecast_96_96Weather_w1251_prollcov...,PatchTST,96,96,1251,prollcov.csv,Weather
0,0.026556,0.001297,0.036018,0.635215,1.895888,long_term_forecast_96_96Weather_w501_ipmutual_...,TimeXer,96,96,501,ipmutual,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.915428,1.037478,1.018567,1.472525,33.566260,long_term_forecast_96_96ETTh2_w1001_prollcorr....,Crossformer,96,96,1001,prollcorr.csv,ETTh2
0,0.872185,1.071869,1.035311,1.172715,14.127322,long_term_forecast_96_96ETTh2_w1001_iprollcov....,Crossformer,96,96,1001,iprollcov.csv,ETTh2
0,1.004878,1.194007,1.092706,1.597492,36.655285,long_term_forecast_96_96ETTh2_w1251_iprollcov....,Crossformer,96,96,1251,iprollcov.csv,ETTh2
0,1.029735,1.236764,1.112099,1.699586,44.818970,long_term_forecast_96_96ETTh2_w501_pfarm.csv_C...,Crossformer,96,96,501,pfarm.csv,ETTh2
0,1.261671,1.819488,1.348884,1.770645,40.832720,long_term_forecast_720_96ETTh2_w501_prollcov.c...,Crossformer,720,96,501,prollcov.csv,ETTh2

In [3]:
all_results[all_results["pconstructor"] == "identity"]

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.026968,0.001334,0.036530,0.642648,1.950775,long_term_forecast_96_96Weather.csv_TimeXer_We...,TimeXer,96,96,None,identity,Weather
0,0.027599,0.001394,0.037341,0.662418,2.035272,long_term_forecast_ETTh1_96_96Weather.csv_iTra...,iTransformer,96,96,None,identity,Weather
0,0.029677,0.001583,0.039785,0.695600,2.135217,long_term_forecast_ETTh1_192_96Weather.csv_iTr...,iTransformer,192,96,None,identity,Weather
0,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,PatchTST,96,96,None,identity,Weather
0,0.030856,0.001789,0.042291,0.641749,1.408367,long_term_forecast_192_96Weather.csv_PatchTST_...,PatchTST,192,96,None,identity,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.456525,0.370773,0.608912,2.417790,614.014300,long_term_forecast_96_96ECL.csv_Autoformer_ECL...,Autoformer,96,96,None,identity,ECL
0,0.544215,0.371127,0.609202,0.392015,0.178087,long_term_forecast_96_96ETTh1.csv_Crossformer_...,Crossformer,96,96,None,identity,ETTh1
0,0.639415,0.531978,0.729368,0.995540,17.803270,long_term_forecast_96_96ETTh2.csv_Crossformer_...,Crossformer,96,96,None,identity,ETTh2
0,0.649280,0.570648,0.755412,1.154391,22.229683,long_term_forecast_192_96ETTm2.csv_Crossformer...,Crossformer,192,96,None,identity,ETTm2
0,0.875777,1.036669,1.018169,1.416997,31.858318,long_term_forecast_192_96ETTh2.csv_Crossformer...,Crossformer,192,96,None,identity,ETTh2

In [4]:
results_df = get_results(with_calc_improv=True)
results_df.to_csv("partial_results.csv", index=False)
results_df.groupby(["dataset", "pred_len", "model_name"]).size()

dataset  pred_len  model_name
ECL      96        Autoformer      51
                   PatchTST        51
                   TimeXer         51
                   iTransformer    51
         192       TimeXer          2
                                   ..
Weather  96        iTransformer    51
         192       PatchTST         2
                   iTransformer    51
         336       PatchTST         2
         720       PatchTST         2
Length: 67, dtype: int64

## Best results table

In [5]:
# Best results overall: by dataset, pred_len and model
best_results = get_best_results(results_df)
best_results_summarized = best_results[["model_name", "dataset", "pred_len", "improvement", "pconstructor", "pwindow", "mse", "mse_identity",]]
best_results_summarized.to_csv("best_results_summarized.csv", index=False)
best_sorted = best_results_summarized.sort_values(by=["mse", "dataset"], ascending=True)
best_sorted

,model_name,dataset,pred_len,improvement,pconstructor,pwindow,mse,mse_identity
0,iTransformer,Weather,96,9.138807,ipmutual,1251,0.001267,0.001394
1,PatchTST,Weather,96,20.056259,iprollcorr.csv,1501,0.001277,0.001598
4,TimeXer,Weather,96,2.782328,ipmutual,501,0.001297,0.001334
112,Crossformer,Weather,96,76.640501,iprollcov.csv,1501,0.001418,0.006072
116,iTransformer,Weather,192,5.189036,prollcorr.csv,1001,0.001501,0.001583
...,...,...,...,...,...,...,...,...
1818,TimeXer,ECL,192,0.000000,identity,None,0.313749,0.313749
1883,Autoformer,ECL,96,12.513328,ipfarm.csv,501,0.324377,0.370773
1922,TimeXer,ECL,336,1.922800,ipfarm.csv,501,0.362772,0.369885
1923,TimeXer,ECL,720,0.000000,identity,None,0.363971,0.363971
1971,Crossformer,ETTh2,192,54.133946,prollcov.csv,501,0.475479,1.036669

In [11]:
best_final = shape_best_result_for_final_format(best_sorted, shrink_column_names=True)
best_final = best_final.fillna("-")
best_final

model_name        Autoformer                                              \
metric           improvement       mse mse_identity pconstructor pwindow
dataset pred_len
ECL     96         12.513328  0.324377     0.370773       ipfarm     501
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
ETTh1   96         30.653632    0.0807     0.116373      pmutual     501
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
ETTh2   96         25.063986  0.147415     0.196721    iprollcov    1251
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
ETTm1   96           6.67532  0.054679     0.058591       ipfarm    1251
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
ETTm2   96          8.066759  0.112769     0.122664    iprollcov     751
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
Traffic 96          6.734518  0.234853     0.251811        pfarm     751
        192                -         -            -            -       -
Weather 96         34.942647  0.005192      0.00798    prollcorr    1001
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -

model_name       Crossformer                                              ...  \
metric           improvement       mse mse_identity pconstructor pwindow  ...
dataset pred_len                                                          ...
ECL     96                 -         -            -            -       -  ...
        192                -         -            -            -       -  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...
ETTh1   96         54.481525  0.168931     0.371127      pmutual    1001  ...
        192                -         -            -            -       -  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...
ETTh2   96         58.216653  0.222278     0.531978     prollcov     501  ...
        192        54.133946  0.475479     1.036669     prollcov     501  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...
ETTm1   96          31.77634  0.054328     0.079632     prollcov    1501  ...
        192        28.772947  0.210663     0.295763     prollcov    1501  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...
ETTm2   96         56.020943  0.097762     0.222292   iprollcorr     501  ...
        192        76.645156  0.133274     0.570648   iprollcorr     501  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...
Traffic 96                 -         -            -            -       -  ...
        192                -         -            -            -       -  ...
Weather 96         76.640501  0.001418     0.006072    iprollcov    1501  ...
        192                -         -            -            -       -  ...
        336                -         -            -            -       -  ...
        720                -         -            -            -       -  ...

model_name           TimeXer                                              \
metric           improvement       mse mse_identity pconstructor pwindow
dataset pred_len
ECL     96           1.08063  0.265915      0.26882       ipfarm     501
        192              0.0  0.313749     0.313749     identity       -
        336           1.9228  0.362772     0.369885       ipfarm     501
        720              0.0  0.363971     0.363971     identity       -
ETTh1   96          2.382867   0.05529     0.056639      pmutual     751
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -
ETTh2   96           8.88356  0.131488     0.144307     prollcov     501
        192         5.431533   0.18119     0.191597     prollcov     501
        336         3.063487  0.233645     0.241029     prollcov     501
        720         4.626003  0.219267     0.229903     prollcov     501
ETTm1   96          0.809044  0.028265     0.028496   iprollcorr     751
        192              0.0  0.045085     0.045085     identity       -
        336              0.0  0.059027     0.059027     identity       -
        720              0.0  0.080636     0.080636     identity       -
ETTm2   96          2.546961   0.06609     0.067818     pentropy    1251
        192         1.866032  0.101717     0.103651     pentropy    1251
        336         1.194833  0.134044     0.135665     pentropy    1251
        720              0.0  0.188662     0.188662     identity       -
Traffic 96          2.661655  0.163954     0.168437   iprollcorr     501
        192                -         -            -            -       -
Weather 96          2.782328  0.001297     0.001334     ipmutual     501
        192                -         -            -            -       -
        336                -         -            -            -       -
        720                -         -            -            -       -

model_name       iTransformer
metric            improvement       mse mse_identity pconstructor pwindow
dataset pred_len
ECL     96           2.087391  0.272955     0.278774      pmutual    1501
        192          1.362804  0.312344      0.31666    prollcorr    1251
        336                 -         -            -            -       -
        720                 -         -            -            -       -
ETTh1   96            2.81207  0.057038     0.058688      pmutual     751
        192          3.015708  0.070301     0.072487      pmutual    1251
        336                 -         -            -            -       -
        720                 -         -            -            -       -
ETTh2   96           3.733014     0.132     0.137118    prollcorr    1251
        192          5.626622  0.183048     0.193961    prollcorr    1501
        336               0.0  0.214865     0.214865     identity       -
        720          0.756682  0.258857     0.260831    prollcorr    1501
ETTm1   96           1.481544  0.029947     0.030397     ipmutual    1501
        192          0.203697  0.044527     0.044618    ipentropy    1251
        336                 -         -            -            -       -
        720                 -         -            -            -       -
ETTm2   96          10.076355  0.068177     0.075816    iprollcov     751
        192         12.906549   0.10467     0.120181   iprollcorr    1501
        336         10.459056  0.140773     0.157216   iprollcorr    1501
        720          4.812724  0.183619     0.192903   iprollcorr    1501
Traffic 96           5.581958  0.147666     0.156396   iprollcorr     501
        192          0.340449  0.154986     0.155515   iprollcorr     501
Weather 96           9.138807  0.001267     0.001394     ipmutual    1251
        192          5.189036  0.001501     0.001583    prollcorr    1001
        336                 -         -            -            -       -
        720                 -         -            -            -       -

[26 rows x 25 columns]

In [12]:
latex_table = best_final.to_latex(multicolumn=True, multirow=True, longtable=True, escape=False)
# Assuming `latex_table` is your LaTeX string
from IPython.display import HTML

html = f"""
<textarea style="width:100%; height:400px;" readonly>{latex_table}</textarea>
"""
display(HTML(html))

## All results sorted by accuracy

In [6]:
results_df.sort_values("mse", ascending=True)

,model_name,pred_len,dataset,mae,mse,rmse,mape,mspe,exp_name,lookback_len,...,pconstructor,mae_identity,mse_identity,rmse_identity,mape_identity,mspe_identity,exp_name_identity,lookback_len_identity,mse_diff,improvement
0,iTransformer,96,Weather,0.026185,0.001267,0.035594,0.617929,1.814222,long_term_forecast_ETTh1_96_96Weather_w1251_ip...,96,...,ipmutual,0.027599,0.001394,0.037341,0.662418,2.035272,long_term_forecast_ETTh1_96_96Weather.csv_iTra...,96,0.000127,9.138807
1,PatchTST,96,Weather,0.026345,0.001277,0.035741,0.629864,1.962374,long_term_forecast_96_96Weather_w1501_iprollco...,96,...,iprollcorr.csv,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,96,0.000320,20.056259
2,PatchTST,96,Weather,0.026596,0.001290,0.035922,0.629982,1.933035,long_term_forecast_96_96Weather_w1251_iprollco...,96,...,iprollcorr.csv,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,96,0.000308,19.246359
3,PatchTST,96,Weather,0.026508,0.001297,0.036018,0.639845,2.016285,long_term_forecast_96_96Weather_w1251_prollcov...,96,...,prollcov.csv,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,96,0.000301,18.815369
4,TimeXer,96,Weather,0.026556,0.001297,0.036018,0.635215,1.895888,long_term_forecast_96_96Weather_w501_ipmutual_...,96,...,ipmutual,0.026968,0.001334,0.036530,0.642648,1.950775,long_term_forecast_96_96Weather.csv_TimeXer_We...,96,0.000037,2.782328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,Crossformer,192,ETTh2,0.875777,1.036669,1.018169,1.416997,31.858318,long_term_forecast_192_96ETTh2.csv_Crossformer...,96,...,identity,0.875777,1.036669,1.018169,1.416997,31.858318,long_term_forecast_192_96ETTh2.csv_Crossformer...,96,0.000000,0.000000
2037,Crossformer,96,ETTh2,0.915428,1.037478,1.018567,1.472525,33.566260,long_term_forecast_96_96ETTh2_w1001_prollcorr....,96,...,prollcorr.csv,0.639415,0.531978,0.729368,0.995540,17.803270,long_term_forecast_96_96ETTh2.csv_Crossformer_...,96,-0.505500,-95.022673
2038,Crossformer,96,ETTh2,0.872185,1.071869,1.035311,1.172715,14.127322,long_term_forecast_96_96ETTh2_w1001_iprollcov....,96,...,iprollcov.csv,0.639415,0.531978,0.729368,0.995540,17.803270,long_term_forecast_96_96ETTh2.csv_Crossformer_...,96,-0.539891,-101.487335
2039,Crossformer,96,ETTh2,1.004878,1.194007,1.092706,1.597492,36.655285,long_term_forecast_96_96ETTh2_w1251_iprollcov....,96,...,iprollcov.csv,0.639415,0.531978,0.729368,0.995540,17.803270,long_term_forecast_96_96ETTh2.csv_Crossformer_...,96,-0.662029,-124.446542
2040,Crossformer,96,ETTh2,1.029735,1.236764,1.112099,1.699586,44.818970,long_term_forecast_96_96ETTh2_w501_pfarm.csv_C...,96,...,pfarm.csv,0.639415,0.531978,0.729368,0.995540,17.803270,long_term_forecast_96_96ETTh2.csv_Crossformer_...,96,-0.704786,-132.483881

## Parameter behavior on accuracy when shaping

In [62]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    "ipentropy.csv",
    "prollcov.csv",
    "iprollcov.csv",
    "prollcorr.csv",
    "iprollcorr.csv",
    "pfarm.csv",
    "ipfarm.csv",
    "pmutual",
    "ipmutual",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    "iTransformer",
    # "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    "ETTh2",
    # "ETTm1",
    # "ETTm2",
    # "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

def count_good_results(x_array):
    return len([element for element in x_array if element > 0])

plot_results(
    tohist_df,
    value_col="pwindow",
    y_agg_col="improvement",
    agg_func=np.mean,
    group_col=[
        # "pwindow",
        "pconstructor",
        # "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    # smooth="kde",
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=0,
)

## Parameters effects on accuracy when shaping

In [32]:
tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    # "ipentropy.csv",
    # "prollcov.csv",
    # "iprollcov.csv",
    # "prollcorr.csv",
    # "iprollcorr.csv",
    # "pfarm.csv",
    # "ipfarm.csv",
    # "pmutual",
    # "ipmutual",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    # "iTransformer",
    "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    # "ETTh2",
    # "ETTm1",
    # "ETTm2",
    "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

plot_results(
    tohist_df,
    value_col="improvement",
    group_col=[
        "pwindow",
        # "pconstructor",
        "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=-100,
)

## Forecast plot

In [10]:
pred_len = 96
# model_name = "TimeXer"
# dataset = "ETTh1"
model_name = "Crossformer"
dataset = "Weather"
cutoff_index = 100

forecast_plot_df = get_forecast_plot(
    model_name=model_name,
    dataset=dataset,
    pred_len=pred_len,
    cutoff_index=cutoff_index,
    best_results=best_results,
    all_results=all_results
)

forecast_plot_df.plot()

long_term_forecast_96_96Weather_w1501_iprollcov.csv_Crossformer_Weather_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_expand2_dc4_fc3_ebtimeF_dtTrue_Exp_0
long_term_forecast_96_96Weather.csv_Crossformer_Weather_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_expand2_dc4_fc3_ebtimeF_dtTrue_Exp_0
Metrics shaped:        mae       mse     rmse      mape      mspe
0  0.02819  0.001418  0.03766  0.583023  1.129209
Metrics identity:         mae       mse      rmse      mape      mspe
0  0.062109  0.006072  0.077921  1.354337  5.816252

## Show the original and shaped data graphs

In [11]:
from config_utils import datasets_path_mapping
from plotly_resampler import register_plotly_resampler
register_plotly_resampler(mode='auto')
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().set_output(transform="pandas")

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

dataset_path = datasets_path_mapping[dataset]

br = best_results[
    (best_results["model_name"] == model_name) & 
    (best_results["dataset"] == dataset) & 
    (best_results["pred_len"] == pred_len)
] # there should be only one with this filter
pwindow = br["pwindow"].values[0]
pconstructor = br["pconstructor"].values[0]
lookback_len = br["lookback_len"].values[0]

dataset_shaped_path = f"{dataset_path}{dataset}_w{pwindow}_{pconstructor}"
dataset_shaped = pd.read_csv(dataset_shaped_path)

max_index_to_plot = forecast_plot_df.index.values.max()
min_index_to_plot = forecast_plot_df.index.values.min()
time_index_to_separate = dataset_shaped.reset_index().iloc[min_index_to_plot]
print(f"Min: {min_index_to_plot} | Max: {max_index_to_plot}")

dataset_shaped = dataset_shaped[-10540:0] # TODO: get the right index to plot
dataset_shaped = dataset_shaped.iloc[min_index_to_plot-lookback_len:max_index_to_plot].set_index("date")
fig = scaler.fit_transform(dataset_shaped).plot()

fig.add_vline(x=time_index_to_separate["date"], line_dash="dash", line_color="green")

fig.show()

/home/ubuntu/master_realm/lib/python3.12/site-packages/dash/_jupyter.py:30: DeprecationWarning:

The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

Min: 9600 | Max: 9695

ValueError: Found array with 0 sample(s) (shape=(0, 21)) while a minimum of 1 is required by MinMaxScaler.