# Shape morphing results
---

### Main Experiments:

1. TSLib framework with latest SOTA transformer models and multiple Shaping settings
2. CATS framework with common vanilla benchmark models and multiple Shaping settings

### Notes:

Reduced number of ablation experiments:

1. Run pred_len=96 with all the window_lengths BUT run only the best window_length of the 96 for other pred_lens
2. Run pred_len=96 with all the constructors BUT run only the best 50% (maybe only the best) constructors of the 96 for other pred_lens

Defensive experiments:

1. Pconstructor noise/random as benchmarks
2. Target variable replacing every exogenous feature
3. Run MLP, LSTM, CNN and Transformers (simple models benchmarks)
4. CATS: should we modify/shape morph the exogenous features or add them to the input?

### TODO:

> Find the best offset index to plot by comparing highest relevance ratio and lowest mse

# Results Tables
---

In [2]:
import os
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"
from results_utils_shape_morphing import get_results, plot_results, get_best_results, get_forecast_plot, shape_best_result_for_final_format_compact

In [3]:
results_directory = "./results_shaping_ablation/"
all_results = get_results(with_calc_improv=False, results_directory=results_directory)
all_results

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.025951,0.001256,0.035440,0.621086,1.825515,long_term_forecast_96_96Weather_w501_prandomwa...,iTransformer,96,96,501,prandomwalk.csv,Weather
0,0.026180,0.001262,0.035526,0.594578,1.492734,long_term_forecast_96_96Weather_w501_ipsmoothr...,iTransformer,96,96,501,ipsmoothrandomwalk.csv,Weather
0,0.026185,0.001267,0.035594,0.617929,1.814222,long_term_forecast_ETTh1_96_96Weather_w1251_ip...,iTransformer,96,96,1251,ipmutual_info.csv,Weather
0,0.025879,0.001267,0.035600,0.602828,1.622127,long_term_forecast_96_96Weather_w1251_ipsmooth...,iTransformer,96,96,1251,ipsmoothrandomwalk.csv,Weather
0,0.026061,0.001270,0.035631,0.616114,1.814624,long_term_forecast_96_96Weather_w1501_ipsmooth...,iTransformer,96,96,1501,ipsmoothrandomwalk.csv,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,1.000926,1.474366,1.214235,1.603151,40.044876,long_term_forecast_720_96ETTm2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm2
0,1.123495,1.534874,1.238900,1.810668,46.887585,long_term_forecast_96_96ETTh2_w1251_ipsmoothra...,Crossformer,96,96,1251,ipsmoothrandomwalk.csv,ETTh2
0,1.188046,1.632569,1.277720,2.014609,62.180800,long_term_forecast_96_96ETTh2_w1501_ipsmoothra...,Crossformer,96,96,1501,ipsmoothrandomwalk.csv,ETTh2
0,1.247429,1.783254,1.335385,1.903021,58.190810,long_term_forecast_720_96ETTh2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTh2
0,1.261671,1.819488,1.348884,1.770645,40.832720,long_term_forecast_720_96ETTh2_w501_prollcov.c...,Crossformer,720,96,501,prollcov.csv,ETTh2

In [3]:
all_results[all_results["dataset"] == "ETTh1"]

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.179195,0.055290,0.235138,0.142016,0.037980,long_term_forecast_96_96ETTh1_w751_pmutual_inf...,TimeXer,96,96,751,pmutual_info.csv,ETTh1
0,0.180503,0.055768,0.236152,0.143686,0.038092,long_term_forecast_96_96ETTh1_w501_psmoothrand...,TimeXer,96,96,501,psmoothrandomwalk.csv,ETTh1
0,0.179862,0.055874,0.236376,0.142478,0.037182,long_term_forecast_96_96ETTh1_w751_ipsmoothran...,PatchTST,96,96,751,ipsmoothrandomwalk.csv,ETTh1
0,0.181169,0.055907,0.236446,0.145461,0.040149,long_term_forecast_96_96ETTh1_w1251_psmoothran...,TimeXer,96,96,1251,psmoothrandomwalk.csv,ETTh1
0,0.179874,0.055911,0.236456,0.142443,0.037160,long_term_forecast_96_96ETTh1_w501_prandomwalk...,PatchTST,96,96,501,prandomwalk.csv,ETTh1
...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.811601,0.737040,0.858510,0.592939,0.363911,long_term_forecast_96_96ETTh1_w1501_psmoothran...,Crossformer,96,96,1501,psmoothrandomwalk.csv,ETTh1
0,0.804825,0.752145,0.867263,0.580512,0.358065,long_term_forecast_96_96ETTh1_w1001_ipsmoothra...,Crossformer,96,96,1001,ipsmoothrandomwalk.csv,ETTh1
0,0.827549,0.776591,0.881244,0.601067,0.375777,long_term_forecast_96_96ETTh1_w501_ipsmoothran...,Crossformer,96,96,501,ipsmoothrandomwalk.csv,ETTh1
0,0.886942,0.891374,0.944126,0.645659,0.434696,long_term_forecast_96_96ETTh1_w1251_ipsmoothra...,Crossformer,96,96,1251,ipsmoothrandomwalk.csv,ETTh1
0,0.993405,1.078470,1.038494,0.733043,0.547944,long_term_forecast_96_96ETTh1_w501_iprandomwal...,Crossformer,96,96,501,iprandomwalk.csv,ETTh1

## Indentity results

In [4]:
all_results[all_results["pconstructor"] == "identity"]

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.026968,0.001334,0.036530,0.642648,1.950775,long_term_forecast_96_96Weather.csv_TimeXer_We...,TimeXer,96,96,None,identity,Weather
0,0.027599,0.001394,0.037341,0.662418,2.035272,long_term_forecast_ETTh1_96_96Weather.csv_iTra...,iTransformer,96,96,None,identity,Weather
0,0.029677,0.001583,0.039785,0.695600,2.135217,long_term_forecast_ETTh1_192_96Weather.csv_iTr...,iTransformer,192,96,None,identity,Weather
0,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,PatchTST,96,96,None,identity,Weather
0,0.029958,0.001606,0.040072,0.701183,2.198924,long_term_forecast_192_96Weather.csv_TimeXer_W...,TimeXer,192,96,None,identity,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.913687,0.940931,0.970016,0.688961,0.525926,long_term_forecast_720_96ETTm1.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm1
0,0.875777,1.036669,1.018169,1.416997,31.858318,long_term_forecast_192_96ETTh2.csv_Crossformer...,Crossformer,192,96,None,identity,ETTh2
0,1.080980,1.419225,1.191312,1.786226,56.553974,long_term_forecast_336_96ETTh2.csv_Crossformer...,Crossformer,336,96,None,identity,ETTh2
0,1.000926,1.474366,1.214235,1.603151,40.044876,long_term_forecast_720_96ETTm2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm2
0,1.247429,1.783254,1.335385,1.903021,58.190810,long_term_forecast_720_96ETTh2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTh2

# Quantity of experiments by group

In [5]:
results_df = get_results(with_calc_improv=True, results_directory=results_directory)
results_df.to_csv("partial_results.csv", index=False)
results_df.groupby(["dataset", "pred_len", "model_name"]).size()
# results_df

dataset  pred_len  model_name
ECL      96        Autoformer      63
                   PatchTST        63
                   TimeXer         63
                   iTransformer    63
         192       Autoformer       2
                                   ..
Weather  720       Autoformer       2
                   Crossformer      2
                   PatchTST         2
                   TimeXer          2
                   iTransformer     2
Length: 117, dtype: int64

## Best results table

In [6]:
# Best results overall: by dataset, pred_len and model
best_results = get_best_results(results_df)
best_results_summarized = best_results[["model_name", "dataset", "pred_len", "improvement", "pconstructor", "pwindow", "mse", "mse_identity",]]
best_results_summarized.to_csv("best_results_summarized.csv", index=False)
best_sorted = best_results_summarized.sort_values(by=["mse", "dataset"], ascending=True)
best_sorted[best_sorted["dataset"] == "ETTh2"].sort_values("mse", ascending=True)

,model_name,dataset,pred_len,improvement,pconstructor,pwindow,mse,mse_identity
1369,TimeXer,ETTh2,96,8.883560,prollcov.csv,501,0.131488,0.144307
1370,iTransformer,ETTh2,96,3.733014,prollcorr.csv,1251,0.132000,0.137118
1413,PatchTST,ETTh2,96,0.369914,pmutual_info.csv,1501,0.135849,0.136353
1590,Autoformer,ETTh2,96,25.063986,iprollcov.csv,1251,0.147415,0.196721
1866,Crossformer,ETTh2,96,66.491784,prandomwalk.csv,501,0.178256,0.531978
1873,TimeXer,ETTh2,192,5.431533,prollcov.csv,501,0.181190,0.191597
1876,iTransformer,ETTh2,192,5.626622,prollcorr.csv,1501,0.183048,0.193961
1925,PatchTST,ETTh2,192,1.823133,pmutual_info.csv,1501,0.192419,0.195992
1968,iTransformer,ETTh2,336,-0.213129,prollcorr.csv,1501,0.215323,0.214865
1969,Autoformer,ETTh2,192,2.238435,iprollcov.csv,1251,0.215998,0.220944
1970,TimeXer,ETTh2,720,4.626003,prollcov.csv,501,0.219267,0.229903
1982,PatchTST,ETTh2,336,2.057748,pmutual_info.csv,1501,0.227580,0.232362
1989,TimeXer,ETTh2,336,3.063487,prollcov.csv,501,0.233645,0.241029
2004,PatchTST,ETTh2,720,5.029306,pmutual_info.csv,1501,0.244959,0.257932
2044,iTransformer,ETTh2,720,0.756682,prollcorr.csv,1501,0.258857,0.260831
2080,Autoformer,ETTh2,720,-0.733445,iprollcov.csv,1251,0.270565,0.268595
2082,Autoformer,ETTh2,336,-0.968274,iprollcov.csv,1251,0.271071,0.268471
2427,Crossformer,ETTh2,192,54.133946,prollcov.csv,501,0.475479,1.036669
2491,Crossformer,ETTh2,336,49.973496,prollcov.csv,501,0.709989,1.419225
2531,Crossformer,ETTh2,720,-2.031875,prollcov.csv,501,1.819488,1.783254

In [1]:
best_final = shape_best_result_for_final_format_compact(best_sorted)
# best_final = best_final.fillna("-")
perf_df = best_final[0]
meta_df = best_final[1]

perf_df.to_csv("best_results_final_perf.csv", index=True)
meta_df.to_csv("best_results_final_meta.csv", index=True)

meta_df.columns = meta_df.columns.swaplevel(0, 1) # swapping for better readability
meta_df = meta_df.sort_index(axis=1, level=0)
meta_df.columns.names = ['Model', 'Morphing']
meta_df

NameError: name 'shape_best_result_for_final_format_compact' is not defined

In [8]:
latex_table_perf = perf_df.to_latex(multicolumn=True, multirow=True, longtable=False, escape=False)
latex_table_meta = meta_df.to_latex(multicolumn=True, multirow=True, longtable=False, escape=False)

from IPython.display import HTML

html = f"""
<textarea style="width:100%; height:400px;" readonly>{latex_table_meta}</textarea>
"""
display(HTML(html))

# Shape morphing analysis
---

## Parameter behavior on accuracy when shaping

In [12]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    "ipentropy.csv",
    "prollcov.csv",
    "iprollcov.csv",
    "prollcorr.csv",
    "iprollcorr.csv",
    "pfarm.csv",
    "ipfarm.csv",
    "pmutual",
    "ipmutual",
    "prandomwalk.csv",
    "iprandomwalk.csv",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    "iTransformer",
    # "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    "ETTh2",
    # "ETTm1",
    # "ETTm2",
    # "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

def count_good_results(x_array):
    return len([element for element in x_array if element > 0])

plot_results(
    tohist_df,
    value_col="pwindow",
    y_agg_col="improvement",
    agg_func=np.mean,
    group_col=[
        # "pwindow",
        "pconstructor",
        # "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    # smooth="kde",
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=0,
)

## Parameters effects on accuracy when shaping

In [10]:
tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    # "ipentropy.csv",
    # "prollcov.csv",
    # "iprollcov.csv",
    # "prollcorr.csv",
    # "iprollcorr.csv",
    # "pfarm.csv",
    # "ipfarm.csv",
    # "pmutual",
    # "ipmutual",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    # "iTransformer",
    "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    # "ETTh2",
    # "ETTm1",
    # "ETTm2",
    "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

plot_results(
    tohist_df,
    value_col="improvement",
    group_col=[
        "pwindow",
        # "pconstructor",
        "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=-100,
)

# Plotting
---

In [11]:
import pandas as pd
pd.options.plotting.backend = "plotly"

from plotly_resampler import register_plotly_resampler
register_plotly_resampler(mode='auto')

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from results_utils_shape_morphing import get_forecast_shape_morphing_plot

root_directory = "/home/ubuntu/repos/TSPindorama/results/"

with_saliency_ratio = False
with_min_max_scaling = False

pwindow = 751
pconstructor = "pmutual_info"
dataset = "ETTh1"
pred_len = 96
model = "TimeXer"
offset_idx = 100

# pwindow = 1001
# pconstructor = "pmutual_info"
# dataset = "ETTh1"
# pred_len = 96
# model = "Crossformer"
# offset_idx = 0

# pwindow = 501
# pconstructor = "prollcov"
# dataset = "ETTh2"
# pred_len = 96
# model = "Crossformer"
# offset_idx = 0

# pwindow = 1501
# pconstructor = "prollcov"
# dataset = "ETTm1"
# pred_len = 96
# model = "Crossformer"
# offset_idx = 0

# pwindow = 1001
# pconstructor = "iprollcov"
# dataset = "Weather"
# pred_len = 96
# model = "Crossformer"
# offset_idx = 0

# pwindow = 501
# pconstructor = "iprollcorr"
# dataset = "Traffic"
# pred_len = 96
# model = "iTransformer"
# offset_idx = 0

# pwindow = 501
# pconstructor = "ipfarm"
# dataset = "ECL"
# pred_len = 96
# model = "Autoformer"
# offset_idx = 0

forecast_plot, dataset_plot, joint_plot = get_forecast_shape_morphing_plot(
    pwindow=pwindow,
    pconstructor=pconstructor,
    dataset=dataset,
    pred_len=pred_len,
    model=model,
    offset_idx=offset_idx,
    root_directory=root_directory,
    with_saliency_ratio=with_saliency_ratio,
    with_min_max_scaling=with_min_max_scaling
)

/home/ubuntu/master_realm/lib/python3.12/site-packages/dash/_jupyter.py:30: DeprecationWarning:

The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

In [12]:
forecast_plot.plot(title=f"Prediction vs True for offset {offset_idx} and pred_len {pred_len} (shaped vs identity)")

FigureWidgetResampler({
    'data': [{'hovertemplate': 'variable=true<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'true',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'true',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'ecb8284d-196c-402f-b547-cae269d92c06',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.77025753, -0.77025753, -0.7626294 , -0.70127696, -0.68602055,
                          -0.72427046, -0.7090141 , -0.6936488 , -0.61693096, -0.44834805,
                          -0.37936738, -0.47896978, -0.40236098, -0.47134152, -0.49433511,
                          -0.5479503 , -0.5786811 , -0.6552899 , -0.78562295, -0.7550012 ,
                          -0.7779947 , -0.7396359 , -0.7626294 , -0.72427046, -0.8162447 ,
                          -0.80861646, -0.98493654, -0.8775971 , -1.0386608 , -1.0155584 ,
                          -1.0232955 , -0.9313213 , -0.8393472 , -0.78562295, -0.80098826,
                          -0.7166423 , -0.7320076 , -0.7090141 , -0.72427046, -0.80861646,
                          -0.8623407 , -0.98493654, -1.0539172 , -1.1382631 , -1.2226092 ,
                          -1.1688849 , -1.2456027 , -1.2992179 , -1.0386608 , -1.0922761 ,
                          -1.2456027 , -1.214981  , -1.2456027 , -1.1688849 , -1.1458913 ,
                          -0.96957123, -0.8775971 , -0.6936488 , -0.6322963 , -0.7090141 ,
                          -0.6322963 , -0.6399246 , -0.86996883, -0.9005906 , -0.9005906 ,
                          -0.9005906 , -0.92358416, -0.94657767, -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -0.82398176, -0.80861646, -0.8393472 ,
                          -0.8393472 ], dtype=float32),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=pred<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'pred',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'pred',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': '192fa0a0-6bb9-4afe-af48-7484f4c2908e',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.7776477 , -0.7081781 , -0.72284806, -0.7320109 , -0.71312416,
                          -0.6035428 , -0.609071  , -0.56012475, -0.5934059 , -0.51597464,
                          -0.4539096 , -0.50448245, -0.512254  , -0.5056523 , -0.51755697,
                          -0.57982296, -0.6479242 , -0.64267504, -0.6636376 , -0.70707107,
                          -0.6949559 , -0.72519535, -0.7577367 , -0.7763358 , -0.7712882 ,
                          -0.7964154 , -0.77959925, -0.74370366, -0.6838801 , -0.68224865,
                          -0.68549037, -0.63365716, -0.57495356, -0.6008182 , -0.55769074,
                          -0.5686532 , -0.571814  , -0.6251805 , -0.6059983 , -0.6133278 ,
                          -0.6806215 , -0.7155138 , -0.74644595, -0.7593335 , -0.80367625,
                          -0.84928197, -0.8333485 , -0.82505596, -0.8485788 , -0.81420815,
                          -0.84732646, -0.86553085, -0.8367341 , -0.8131096 , -0.76001483,
                          -0.74868405, -0.6950466 , -0.66699195, -0.61324704, -0.6225074 ,
                          -0.6457241 , -0.66648823, -0.69688654, -0.7293153 , -0.7494606 ,
                          -0.7948307 , -0.83789563, -0.8446476 , -0.86258477, -0.8584001 ,
                          -0.8288233 , -0.8799881 , -0.8614637 , -0.8776177 , -0.86644924,
                          -0.8582858 , -0.8213789 , -0.7643618 , -0.7326228 , -0.69618475,
                          -0.68577397, -0.6697626 , -0.6460587 , -0.6639149 , -0.65265244,
                          -0.6574101 , -0.65656966, -0.6956845 , -0.7144614 , -0.7981984 ,
                          -0.80856395, -0.8206543 , -0.9085486 , -0.8321987 , -0.8257612 ,
                          -0.8664366 ], dtype=float32),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=true_identity<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'true_identity',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'true_identity',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'f358f5cc-b5f4-4906-b324-7aae8f6c2ac8',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.77025753, -0.77025753, -0.7626294 , -0.70127696, -0.68602055,
                          -0.72427046, -0.7090141 , -0.6936488 , -0.61693096, -0.44834805,
                          -0.37936738, -0.47896978, -0.40236098, -0.47134152, -0.49433511,
                          -0.5479503 , -0.5786811 , -0.6552899 , -0.78562295, -0.7550012 ,
                          -0.7779947 , -0.7396359 , -0.7626294 , -0.72427046, -0.8162447 ,
                          -0.80861646, -0.98493654, -0.8775971 , -1.0386608 , -1.0155584 ,
                          -1.0232955 , -0.9313213 , -0.8393472 , -0.78562295, -0.80098826,
                          -0.7166423 , -0.7320076 , -0.7090141 , -0.72427046, -0.80861646,
                          -0.8623407 , -0.98493654, -1.0539172 , -1.1382631 , -1.2226092 ,
                          -1.1688849 , -1.2456027 , -1.2992179 , -1.0386608 , -1.0922761 ,
                          -1.2456027 , -1.214981  , -1.2456027 , -1.1688849 , -1.1458913 ,
                          -0.96957123, -0.8775971 , -0.6936488 , -0.6322963 , -0.7090141 ,
                          -0.6322963 , -0.6399246 , -0.86996883, -0.9005906 , -0.9005906 ,
                          -0.9005906 , -0.92358416, -0.94657767, -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -1.000302  , -1.000302  , -1.000302  ,
                          -1.000302  , -1.000302  , -0.82398176, -0.80861646, -0.8393472 ,
                          -0.8393472 ], dtype=float32),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=pred_identity<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'pred_identity',
              'line': {'color': '#ab63fa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'pred_identity',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': '8701f6f8-f911-4bc4-b1ba-10c44830beca',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.7818404 , -0.71307373, -0.7258277 , -0.7378796 , -0.72377336,
                          -0.60927296, -0.6281742 , -0.56900984, -0.60854524, -0.5327456 ,

In [13]:
dataset_plot.plot(title=f"Dataset {dataset} for offset {offset_idx} (Shaped vs Identity)")

FigureWidgetResampler({
    'data': [{'hovertemplate': 'variable=HUFL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HUFL_shaped',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HUFL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': 'c62c863e-0603-41ff-b5c1-ef107099d80a',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 2.23978522e-01,  4.00249160e-02,  2.06305356e-01,  8.64933984e-02,
                          -6.69178970e-01, -1.58574453e+00, -2.01464984e+00, -2.21747782e+00,
                          -2.65179689e+00, -2.38423340e+00, -1.97572272e+00, -1.55783078e+00,
                          -7.91433035e-01, -1.04885813e-01, -8.07645576e-02, -9.55874229e-02,
                          -1.26993453e-01, -4.50958385e-02,  1.88214127e-01,  2.86037440e-01,
                           4.17400226e-01,  3.57827111e-01,  2.60004781e-01,  3.10795605e-01,
                           4.35486052e-01,  2.90825823e-01,  3.24526853e-01,  3.66532982e-01,
                          -2.42359376e-01, -6.67896397e-01, -3.99184302e-01, -2.76410032e-01,
                          -1.38368685e+00, -1.54598785e+00, -1.61355522e+00, -1.69614614e+00,
                          -8.91967450e-01, -1.73558390e-01, -1.10434564e-01, -1.66781548e-01,
                          -2.37267953e-01, -2.52422223e-01, -2.52744132e-01, -1.07810510e-01,
                          -3.69814460e-02, -5.41756073e-02, -1.73421873e-02, -7.22437541e-02,
                          -1.15570833e-01,  2.36519176e-03,  2.41950093e-02,  1.14724444e-01,
                          -6.13526347e-01, -1.57009794e+00, -1.83818146e+00, -1.51479157e+00,
                          -2.17050799e+00, -2.13054596e+00, -1.96668612e+00, -1.43516670e+00,
                          -8.71659161e-01, -1.97713206e-01, -1.87834691e-01, -2.20474317e-01,
                          -3.06024541e-01, -7.37846636e-02, -6.30432140e-02,  1.06663000e-01,
                           1.00210834e-01,  9.82295638e-02,  1.01355908e-01,  1.07152586e-01,
                           1.08729308e-01,  1.11202593e-01,  1.17589690e-01,  1.18081441e-01,
                           1.22697970e-01,  1.28444549e-01,  1.33787438e-01,  1.37027127e-01,
                           1.38612721e-01,  1.44633729e-01,  1.34913901e-01,  1.40093862e-01,
                           1.48047624e-01,  1.53983753e-01,  1.60466499e-01,  1.69301556e-01,
                           1.75018740e-01,  1.79357406e-01,  1.87020905e-01,  1.89743327e-01,
                           2.72249337e-01,  2.77469033e-01,  1.52263498e-01,  1.44677339e-01]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=HULL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HULL_shaped',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HULL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': '5899f912-5420-4021-a16f-b21aaf362e27',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.23943814, -0.37551176, -0.22938299, -0.38399107, -0.13228465,
                          -0.13247931,  0.10074147,  0.12109557,  0.20256383,  0.34852277,
                           0.16173642, -0.24023751, -0.46701085, -0.46565603, -0.49497524,
                          -0.53144869, -0.52230882, -0.59526837, -0.27523726, -0.21721566,
                          -0.06089794, -0.15456452, -0.17890843, -0.16803531, -0.21500108,
                          -0.34046325, -0.37301769, -0.25091701, -0.20927961, -0.31863018,
                          -0.33979121, -0.45972485, -0.42543432, -0.28495186, -0.33294158,
                          -0.43436131, -0.50400883, -0.57427204, -0.60551962, -0.65758894,
                          -0.65583333, -0.69078345, -0.50880736, -0.47580776, -0.37644595,
                          -0.39192266, -0.28860869, -0.44869936, -0.51146607, -0.37965026,
                          -0.4714033 , -0.38799539, -0.32104346, -0.29601852, -0.19848827,
                          -0.27928691, -0.15674709, -0.04770804, -0.1532505 , -0.43927674,
                          -0.52663778, -0.56496084, -0.60602306, -0.62500274, -0.63074025,
                          -0.63633715, -0.48263659, -0.42029667, -0.36278233, -0.35760648,
                          -0.34128957, -0.33250985, -0.33204137, -0.33118898, -0.32746048,
                          -0.31960432, -0.31155373, -0.30282652, -0.29873678, -0.28748653,
                          -0.27531203, -0.26500012, -0.25699528, -0.25038297, -0.2453857 ,
                          -0.23372746, -0.22421489, -0.22109276, -0.21769329, -0.21056465,
                          -0.20041455, -0.18884564, -0.0879888 , -0.17827685, -0.24133335,
                          -0.23703236]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=MUFL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'MUFL_shaped',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MUFL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': 'bb6c5d27-cec4-4de8-803f-77e1b4f36465',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 5.62607040e-01,  3.23691754e-01,  4.93303432e-01,  2.72716760e-01,
                          -6.57672418e-01, -1.87528553e+00, -2.51301450e+00, -2.77959178e+00,
                          -3.24730534e+00, -2.89869481e+00, -2.45992551e+00, -1.82601833e+00,
                          -8.35168112e-01,  2.50707419e-03,  4.91060505e-02,  3.17175467e-02,
                          -1.72034549e-02,  1.19841709e-01,  5.25431204e-01,  6.49799641e-01,
                           8.76856700e-01,  7.35401891e-01,  7.38039119e-01,  8.01480146e-01,
                           8.17148491e-01,  5.86588895e-01,  6.24769123e-01,  5.77473210e-01,
                          -1.95878755e-01, -8.19008136e-01, -3.93736541e-01, -2.99695197e-01,
                          -1.68518981e+00, -1.87736097e+00, -1.98904233e+00, -1.99522526e+00,
                          -1.01486567e+00, -9.17356769e-02, -2.26055631e-02, -6.61844835e-02,
                          -1.27855465e-01, -1.19748301e-01, -9.56646887e-02,  1.27173184e-01,
                           2.18133285e-01,  2.07476605e-01,  3.33175225e-01,  1.57636335e-01,
                           1.13515408e-01,  2.58241549e-01,  2.88361218e-01,  2.30473256e-01,
                          -6.60483278e-01, -1.84308684e+00, -2.30052167e+00, -1.94219969e+00,
                          -2.68587777e+00, -2.69560228e+00, -2.41560596e+00, -1.72893529e+00,
                          -9.68103790e-01, -9.84510908e-02, -6.21876590e-02, -8.41524782e-02,
                          -1.48954816e-01,  1.46462019e-01,  2.06350677e-01,  4.12503394e-01,
                           4.20964624e-01,  4.24612254e-01,  4.30172744e-01,  4.39332721e-01,
                           4.39098166e-01,  4.42890590e-01,  4.52506729e-01,  4.61257721e-01,
                           4.67164431e-01,  4.71545484e-01,  4.80859573e-01,  4.80859573e-01,
                           4.80028792e-01,  4.83745359e-01,  4.81751369e-01,  4.81751369e-01,
                           4.89647996e-01,  4.95541320e-01,  5.05359374e-01,  5.13007986e-01,
                           5.22883153e-01,  5.29606148e-01,  5.40566210e-01,  5.49559811e-01,
                           6.72861525e-01,  6.49714077e-01,  4.92812833e-01,  5.36580463e-01]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=MULL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'MULL_shaped',
              'line': {'color': '#ab63fa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MULL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': 'f6b0cba8-a114-40fb-b3ae-0c8eab4cf6a3',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',

In [14]:
joint_plot.plot(title=f"Prediction vs True for offset {offset_idx} and pred_len {pred_len} with input variables (shaped vs identity)")

FigureWidgetResampler({
    'data': [{'hovertemplate': 'variable=HUFL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HUFL_shaped',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HUFL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': '48dddddf-0567-4ffc-b12d-4ad23df36cbc',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 2.23978522e-01,  4.00249160e-02,  2.06305356e-01,  8.64933984e-02,
                          -6.69178970e-01, -1.58574453e+00, -2.01464984e+00, -2.21747782e+00,
                          -2.65179689e+00, -2.38423340e+00, -1.97572272e+00, -1.55783078e+00,
                          -7.91433035e-01, -1.04885813e-01, -8.07645576e-02, -9.55874229e-02,
                          -1.26993453e-01, -4.50958385e-02,  1.88214127e-01,  2.86037440e-01,
                           4.17400226e-01,  3.57827111e-01,  2.60004781e-01,  3.10795605e-01,
                           4.35486052e-01,  2.90825823e-01,  3.24526853e-01,  3.66532982e-01,
                          -2.42359376e-01, -6.67896397e-01, -3.99184302e-01, -2.76410032e-01,
                          -1.38368685e+00, -1.54598785e+00, -1.61355522e+00, -1.69614614e+00,
                          -8.91967450e-01, -1.73558390e-01, -1.10434564e-01, -1.66781548e-01,
                          -2.37267953e-01, -2.52422223e-01, -2.52744132e-01, -1.07810510e-01,
                          -3.69814460e-02, -5.41756073e-02, -1.73421873e-02, -7.22437541e-02,
                          -1.15570833e-01,  2.36519176e-03,  2.41950093e-02,  1.14724444e-01,
                          -6.13526347e-01, -1.57009794e+00, -1.83818146e+00, -1.51479157e+00,
                          -2.17050799e+00, -2.13054596e+00, -1.96668612e+00, -1.43516670e+00,
                          -8.71659161e-01, -1.97713206e-01, -1.87834691e-01, -2.20474317e-01,
                          -3.06024541e-01, -7.37846636e-02, -6.30432140e-02,  1.06663000e-01,
                           1.00210834e-01,  9.82295638e-02,  1.01355908e-01,  1.07152586e-01,
                           1.08729308e-01,  1.11202593e-01,  1.17589690e-01,  1.18081441e-01,
                           1.22697970e-01,  1.28444549e-01,  1.33787438e-01,  1.37027127e-01,
                           1.38612721e-01,  1.44633729e-01,  1.34913901e-01,  1.40093862e-01,
                           1.48047624e-01,  1.53983753e-01,  1.60466499e-01,  1.69301556e-01,
                           1.75018740e-01,  1.79357406e-01,  1.87020905e-01,  1.89743327e-01,
                           2.72249337e-01,  2.77469033e-01,  1.52263498e-01,  1.44677339e-01]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=HULL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HULL_shaped',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HULL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': '8ebdb7a0-aed7-4674-8144-ec90b1630871',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([-0.23943814, -0.37551176, -0.22938299, -0.38399107, -0.13228465,
                          -0.13247931,  0.10074147,  0.12109557,  0.20256383,  0.34852277,
                           0.16173642, -0.24023751, -0.46701085, -0.46565603, -0.49497524,
                          -0.53144869, -0.52230882, -0.59526837, -0.27523726, -0.21721566,
                          -0.06089794, -0.15456452, -0.17890843, -0.16803531, -0.21500108,
                          -0.34046325, -0.37301769, -0.25091701, -0.20927961, -0.31863018,
                          -0.33979121, -0.45972485, -0.42543432, -0.28495186, -0.33294158,
                          -0.43436131, -0.50400883, -0.57427204, -0.60551962, -0.65758894,
                          -0.65583333, -0.69078345, -0.50880736, -0.47580776, -0.37644595,
                          -0.39192266, -0.28860869, -0.44869936, -0.51146607, -0.37965026,
                          -0.4714033 , -0.38799539, -0.32104346, -0.29601852, -0.19848827,
                          -0.27928691, -0.15674709, -0.04770804, -0.1532505 , -0.43927674,
                          -0.52663778, -0.56496084, -0.60602306, -0.62500274, -0.63074025,
                          -0.63633715, -0.48263659, -0.42029667, -0.36278233, -0.35760648,
                          -0.34128957, -0.33250985, -0.33204137, -0.33118898, -0.32746048,
                          -0.31960432, -0.31155373, -0.30282652, -0.29873678, -0.28748653,
                          -0.27531203, -0.26500012, -0.25699528, -0.25038297, -0.2453857 ,
                          -0.23372746, -0.22421489, -0.22109276, -0.21769329, -0.21056465,
                          -0.20041455, -0.18884564, -0.0879888 , -0.17827685, -0.24133335,
                          -0.23703236]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=MUFL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'MUFL_shaped',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MUFL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': '5855a9b9-e99b-4542-8f8b-cbec09d4c100',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',
                          '2017-10-31 10:00:00', '2017-10-31 11:00:00', '2017-10-31 12:00:00',
                          '2017-10-31 13:00:00', '2017-10-31 14:00:00', '2017-10-31 15:00:00',
                          '2017-10-31 16:00:00', '2017-10-31 17:00:00', '2017-10-31 18:00:00',
                          '2017-10-31 19:00:00', '2017-10-31 20:00:00', '2017-10-31 21:00:00',
                          '2017-10-31 22:00:00', '2017-10-31 23:00:00', '2017-11-01 00:00:00',
                          '2017-11-01 01:00:00', '2017-11-01 02:00:00', '2017-11-01 03:00:00'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 5.62607040e-01,  3.23691754e-01,  4.93303432e-01,  2.72716760e-01,
                          -6.57672418e-01, -1.87528553e+00, -2.51301450e+00, -2.77959178e+00,
                          -3.24730534e+00, -2.89869481e+00, -2.45992551e+00, -1.82601833e+00,
                          -8.35168112e-01,  2.50707419e-03,  4.91060505e-02,  3.17175467e-02,
                          -1.72034549e-02,  1.19841709e-01,  5.25431204e-01,  6.49799641e-01,
                           8.76856700e-01,  7.35401891e-01,  7.38039119e-01,  8.01480146e-01,
                           8.17148491e-01,  5.86588895e-01,  6.24769123e-01,  5.77473210e-01,
                          -1.95878755e-01, -8.19008136e-01, -3.93736541e-01, -2.99695197e-01,
                          -1.68518981e+00, -1.87736097e+00, -1.98904233e+00, -1.99522526e+00,
                          -1.01486567e+00, -9.17356769e-02, -2.26055631e-02, -6.61844835e-02,
                          -1.27855465e-01, -1.19748301e-01, -9.56646887e-02,  1.27173184e-01,
                           2.18133285e-01,  2.07476605e-01,  3.33175225e-01,  1.57636335e-01,
                           1.13515408e-01,  2.58241549e-01,  2.88361218e-01,  2.30473256e-01,
                          -6.60483278e-01, -1.84308684e+00, -2.30052167e+00, -1.94219969e+00,
                          -2.68587777e+00, -2.69560228e+00, -2.41560596e+00, -1.72893529e+00,
                          -9.68103790e-01, -9.84510908e-02, -6.21876590e-02, -8.41524782e-02,
                          -1.48954816e-01,  1.46462019e-01,  2.06350677e-01,  4.12503394e-01,
                           4.20964624e-01,  4.24612254e-01,  4.30172744e-01,  4.39332721e-01,
                           4.39098166e-01,  4.42890590e-01,  4.52506729e-01,  4.61257721e-01,
                           4.67164431e-01,  4.71545484e-01,  4.80859573e-01,  4.80859573e-01,
                           4.80028792e-01,  4.83745359e-01,  4.81751369e-01,  4.81751369e-01,
                           4.89647996e-01,  4.95541320e-01,  5.05359374e-01,  5.13007986e-01,
                           5.22883153e-01,  5.29606148e-01,  5.40566210e-01,  5.49559811e-01,
                           6.72861525e-01,  6.49714077e-01,  4.92812833e-01,  5.36580463e-01]),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=MULL_shaped<br>date=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'MULL_shaped',
              'line': {'color': '#ab63fa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'MULL_shaped',
              'showlegend': True,
              'type': 'scattergl',
              'uid': '4a50ace7-8cd4-49a2-831c-954a707569d7',
              'x': array(['2017-10-28 04:00:00', '2017-10-28 05:00:00', '2017-10-28 06:00:00',
                          '2017-10-28 07:00:00', '2017-10-28 08:00:00', '2017-10-28 09:00:00',
                          '2017-10-28 10:00:00', '2017-10-28 11:00:00', '2017-10-28 12:00:00',
                          '2017-10-28 13:00:00', '2017-10-28 14:00:00', '2017-10-28 15:00:00',
                          '2017-10-28 16:00:00', '2017-10-28 17:00:00', '2017-10-28 18:00:00',
                          '2017-10-28 19:00:00', '2017-10-28 20:00:00', '2017-10-28 21:00:00',
                          '2017-10-28 22:00:00', '2017-10-28 23:00:00', '2017-10-29 00:00:00',
                          '2017-10-29 01:00:00', '2017-10-29 02:00:00', '2017-10-29 03:00:00',
                          '2017-10-29 04:00:00', '2017-10-29 05:00:00', '2017-10-29 06:00:00',
                          '2017-10-29 07:00:00', '2017-10-29 08:00:00', '2017-10-29 09:00:00',
                          '2017-10-29 10:00:00', '2017-10-29 11:00:00', '2017-10-29 12:00:00',
                          '2017-10-29 13:00:00', '2017-10-29 14:00:00', '2017-10-29 15:00:00',
                          '2017-10-29 16:00:00', '2017-10-29 17:00:00', '2017-10-29 18:00:00',
                          '2017-10-29 19:00:00', '2017-10-29 20:00:00', '2017-10-29 21:00:00',
                          '2017-10-29 22:00:00', '2017-10-29 23:00:00', '2017-10-30 00:00:00',
                          '2017-10-30 01:00:00', '2017-10-30 02:00:00', '2017-10-30 03:00:00',
                          '2017-10-30 04:00:00', '2017-10-30 05:00:00', '2017-10-30 06:00:00',
                          '2017-10-30 07:00:00', '2017-10-30 08:00:00', '2017-10-30 09:00:00',
                          '2017-10-30 10:00:00', '2017-10-30 11:00:00', '2017-10-30 12:00:00',
                          '2017-10-30 13:00:00', '2017-10-30 14:00:00', '2017-10-30 15:00:00',
                          '2017-10-30 16:00:00', '2017-10-30 17:00:00', '2017-10-30 18:00:00',
                          '2017-10-30 19:00:00', '2017-10-30 20:00:00', '2017-10-30 21:00:00',
                          '2017-10-30 22:00:00', '2017-10-30 23:00:00', '2017-10-31 00:00:00',
                          '2017-10-31 01:00:00', '2017-10-31 02:00:00', '2017-10-31 03:00:00',
                          '2017-10-31 04:00:00', '2017-10-31 05:00:00', '2017-10-31 06:00:00',
                          '2017-10-31 07:00:00', '2017-10-31 08:00:00', '2017-10-31 09:00:00',