Reduce the number of experiments:
1. Run pred_len=96 with all the window_lengths BUT run only the best window_length of the 96 for other pred_lens
2. Run pred_len=96 with all the constructors BUT run only the best 50% (maybe only the best) constructors of the 96 for other pred_lens

Defensive experiments:
1. Pconstructor noise/random as benchmarks
2. Run MLP, LSTM and CNN with other framework
3. CATS: should we modify/shape the exogenous features or add them to the input?

Lacks:

- Feature ablation experiments for the FARM paper
- Experiments for the shaping paper with predicition lengths greater than 96

In [1]:
import os
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"
from results_utils import get_results, plot_results, get_best_results, get_forecast_plot, shape_best_result_for_final_format_compact

In [3]:
all_results = get_results(with_calc_improv=False)
all_results

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.026185,0.001267,0.035594,0.617929,1.814222,long_term_forecast_ETTh1_96_96Weather_w1251_ip...,iTransformer,96,96,1251,ipmutual_info.csv,Weather
0,0.026345,0.001277,0.035741,0.629864,1.962374,long_term_forecast_96_96Weather_w1501_iprollco...,PatchTST,96,96,1501,iprollcorr.csv,Weather
0,0.026596,0.001290,0.035922,0.629982,1.933035,long_term_forecast_96_96Weather_w1251_iprollco...,PatchTST,96,96,1251,iprollcorr.csv,Weather
0,0.026508,0.001297,0.036018,0.639845,2.016285,long_term_forecast_96_96Weather_w1251_prollcov...,PatchTST,96,96,1251,prollcov.csv,Weather
0,0.026556,0.001297,0.036018,0.635215,1.895888,long_term_forecast_96_96Weather_w501_ipmutual_...,TimeXer,96,96,501,ipmutual_info.csv,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,1.029735,1.236764,1.112099,1.699586,44.818970,long_term_forecast_96_96ETTh2_w501_pfarm.csv_C...,Crossformer,96,96,501,pfarm.csv,ETTh2
0,1.080980,1.419225,1.191312,1.786226,56.553974,long_term_forecast_336_96ETTh2.csv_Crossformer...,Crossformer,336,96,None,identity,ETTh2
0,1.000926,1.474366,1.214235,1.603151,40.044876,long_term_forecast_720_96ETTm2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm2
0,1.247429,1.783254,1.335385,1.903021,58.190810,long_term_forecast_720_96ETTh2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTh2
0,1.261671,1.819488,1.348884,1.770645,40.832720,long_term_forecast_720_96ETTh2_w501_prollcov.c...,Crossformer,720,96,501,prollcov.csv,ETTh2

## Indentity results

In [4]:
all_results[all_results["pconstructor"] == "identity"]

,mae,mse,rmse,mape,mspe,exp_name,model_name,pred_len,lookback_len,pwindow,pconstructor,dataset
0,0.026968,0.001334,0.036530,0.642648,1.950775,long_term_forecast_96_96Weather.csv_TimeXer_We...,TimeXer,96,96,None,identity,Weather
0,0.027599,0.001394,0.037341,0.662418,2.035272,long_term_forecast_ETTh1_96_96Weather.csv_iTra...,iTransformer,96,96,None,identity,Weather
0,0.029677,0.001583,0.039785,0.695600,2.135217,long_term_forecast_ETTh1_192_96Weather.csv_iTr...,iTransformer,192,96,None,identity,Weather
0,0.028645,0.001598,0.039974,0.613426,1.402652,long_term_forecast_96_96Weather.csv_PatchTST_W...,PatchTST,96,96,None,identity,Weather
0,0.029958,0.001606,0.040072,0.701183,2.198924,long_term_forecast_192_96Weather.csv_TimeXer_W...,TimeXer,192,96,None,identity,Weather
...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.913687,0.940931,0.970016,0.688961,0.525926,long_term_forecast_720_96ETTm1.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm1
0,0.875777,1.036669,1.018169,1.416997,31.858318,long_term_forecast_192_96ETTh2.csv_Crossformer...,Crossformer,192,96,None,identity,ETTh2
0,1.080980,1.419225,1.191312,1.786226,56.553974,long_term_forecast_336_96ETTh2.csv_Crossformer...,Crossformer,336,96,None,identity,ETTh2
0,1.000926,1.474366,1.214235,1.603151,40.044876,long_term_forecast_720_96ETTm2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTm2
0,1.247429,1.783254,1.335385,1.903021,58.190810,long_term_forecast_720_96ETTh2.csv_Crossformer...,Crossformer,720,96,None,identity,ETTh2

# Quantity of experiments by group

In [5]:
results_df = get_results(with_calc_improv=True)
results_df.to_csv("partial_results.csv", index=False)
results_df.groupby(["dataset", "pred_len", "model_name"]).size()
# results_df

dataset  pred_len  model_name
ECL      96        Autoformer      51
                   PatchTST        51
                   TimeXer         51
                   iTransformer    51
         192       Autoformer       2
                                   ..
Weather  720       Autoformer       2
                   Crossformer      2
                   PatchTST         2
                   TimeXer          2
                   iTransformer     2
Length: 117, dtype: int64

## Best results table

In [18]:
# Best results overall: by dataset, pred_len and model
best_results = get_best_results(results_df)
best_results_summarized = best_results[["model_name", "dataset", "pred_len", "improvement", "pconstructor", "pwindow", "mse", "mse_identity",]]
best_results_summarized.to_csv("best_results_summarized.csv", index=False)
best_sorted = best_results_summarized.sort_values(by=["mse", "dataset"], ascending=True)
best_sorted[best_sorted["dataset"] == "Weather"].sort_values("improvement", ascending=False)

,model_name,dataset,pred_len,improvement,pconstructor,pwindow,mse,mse_identity
1499,Crossformer,ETTh1,192,59.403035,pmutual_info.csv,1001,0.167054,0.411494
1541,Crossformer,ETTh1,96,54.481525,pmutual_info.csv,1001,0.168931,0.371127
977,Autoformer,ETTh1,96,30.653632,pmutual_info.csv,501,0.080700,0.116373
1696,Crossformer,ETTh1,720,26.422921,pmutual_info.csv,1001,0.243949,0.331556
1704,Crossformer,ETTh1,336,14.585342,pmutual_info.csv,1001,0.251737,0.294724
1108,Autoformer,ETTh1,720,8.920765,pmutual_info.csv,501,0.117747,0.129280
1003,TimeXer,ETTh1,720,7.639844,pmutual_info.csv,751,0.087167,0.094377
1000,Autoformer,ETTh1,192,6.832790,pmutual_info.csv,501,0.086662,0.093018
973,iTransformer,ETTh1,336,5.147198,pmutual_info.csv,1251,0.079764,0.084092
1032,iTransformer,ETTh1,720,4.860141,pmutual_info.csv,1251,0.096377,0.101300
855,iTransformer,ETTh1,192,3.015708,pmutual_info.csv,1251,0.070301,0.072487
634,iTransformer,ETTh1,96,2.812070,pmutual_info.csv,751,0.057038,0.058688
542,TimeXer,ETTh1,96,2.382867,pmutual_info.csv,751,0.055290,0.056639
1113,Autoformer,ETTh1,336,0.236342,pmutual_info.csv,501,0.118023,0.118303
1004,PatchTST,ETTh1,336,0.105493,pfarm.csv,1001,0.088363,0.088456
585,PatchTST,ETTh1,96,0.059969,pfarm.csv,1001,0.056737,0.056771
1012,PatchTST,ETTh1,720,-0.003714,pfarm.csv,1001,0.090202,0.090199
943,PatchTST,ETTh1,192,-0.043818,pfarm.csv,1001,0.074476,0.074444
998,TimeXer,ETTh1,336,-0.501565,pmutual_info.csv,751,0.085827,0.085399
966,TimeXer,ETTh1,192,-6.392954,pmutual_info.csv,751,0.078011,0.073323

In [17]:
best_final = shape_best_result_for_final_format_compact(best_sorted)
# best_final = best_final.fillna("-")
perf_df = best_final[0]
meta_df = best_final[1]

perf_df.to_csv("best_results_final_perf.csv", index=True)
meta_df.to_csv("best_results_final_meta.csv", index=True)

meta_df.columns = meta_df.columns.swaplevel(0, 1) # swapping for better readability
meta_df = meta_df.sort_index(axis=1, level=0)
meta_df.columns.names = ['Model', 'Morphing']
meta_df

Model                Autoformer           Crossformer              PatchTST  \
Morphing           pconstructor pwindow  pconstructor pwindow  pconstructor
dataset  pred_len
ECL      96              ipfarm     501           NaN     NaN      pentropy
         192             ipfarm     501           NaN     NaN           NaN
         336             ipfarm     501           NaN     NaN           NaN
         720             ipfarm     501           NaN     NaN           NaN
ETTh1    96        pmutual_info     501  pmutual_info    1001         pfarm
         192       pmutual_info     501  pmutual_info    1001         pfarm
         336       pmutual_info     501  pmutual_info    1001         pfarm
         720       pmutual_info     501  pmutual_info    1001         pfarm
ETTh2    96           iprollcov    1251      prollcov     501  pmutual_info
         192          iprollcov    1251      prollcov     501  pmutual_info
         336          iprollcov    1251      prollcov     501  pmutual_info
         720          iprollcov    1251      prollcov     501  pmutual_info
ETTm1    96              ipfarm    1251      prollcov    1501  pmutual_info
         192             ipfarm    1251      prollcov    1501  pmutual_info
         336             ipfarm    1251      prollcov    1501  pmutual_info
         720             ipfarm    1251      prollcov    1501  pmutual_info
ETTm2    96           iprollcov     751    iprollcorr     501     prollcorr
         192          iprollcov     751    iprollcorr     501     prollcorr
         336          iprollcov     751    iprollcorr     501     prollcorr
         720          iprollcov     751    iprollcorr     501     prollcorr
TrafficL 96               pfarm     751           NaN     NaN           NaN
         192                NaN     NaN           NaN     NaN           NaN
Weather  96           prollcorr    1001     iprollcov    1501    iprollcorr
         192          prollcorr    1001     iprollcov    1501    iprollcorr
         336          prollcorr    1001     iprollcov    1501    iprollcorr
         720          prollcorr    1001     iprollcov    1501    iprollcorr

Model                            TimeXer           iTransformer
Morphing          pwindow   pconstructor pwindow   pconstructor pwindow
dataset  pred_len
ECL      96          1501         ipfarm     501   pmutual_info    1501
         192          NaN         ipfarm     501      prollcorr    1251
         336          NaN         ipfarm     501   pmutual_info    1501
         720          NaN         ipfarm     501   pmutual_info    1501
ETTh1    96          1001   pmutual_info     751   pmutual_info     751
         192         1001   pmutual_info     751   pmutual_info    1251
         336         1001   pmutual_info     751   pmutual_info    1251
         720         1001   pmutual_info     751   pmutual_info    1251
ETTh2    96          1501       prollcov     501      prollcorr    1251
         192         1501       prollcov     501      prollcorr    1501
         336         1501       prollcov     501      prollcorr    1501
         720         1501       prollcov     501      prollcorr    1501
ETTm1    96           501     iprollcorr     751  ipmutual_info    1501
         192          501     iprollcorr     751      ipentropy    1251
         336          501     iprollcorr     751  ipmutual_info    1501
         720          501     iprollcorr     751  ipmutual_info    1501
ETTm2    96          1001       pentropy    1251      iprollcov     751
         192         1001       pentropy    1251     iprollcorr    1501
         336         1001       pentropy    1251     iprollcorr    1501
         720         1001       pentropy    1251     iprollcorr    1501
TrafficL 96           NaN     iprollcorr     501     iprollcorr     501
         192          NaN            NaN     NaN     iprollcorr     501
Weather  96          1501  ipmutual_info     501  ipmutual_info    1251
         192         1501  ipmutual_info     501      prollcorr    1001
         336         1501  ipmutual_info     501  ipmutual_info    1251
         720         1501  ipmutual_info     501  ipmutual_info    1251

Model                Autoformer           Crossformer              PatchTST  \
Meta               pconstructor pwindow  pconstructor pwindow  pconstructor
dataset  pred_len
ECL      96              ipfarm     501           NaN     NaN      pentropy
         192             ipfarm     501           NaN     NaN           NaN
         336             ipfarm     501           NaN     NaN           NaN
         720             ipfarm     501           NaN     NaN           NaN
ETTh1    96        pmutual_info     501  pmutual_info    1001         pfarm
         192       pmutual_info     501  pmutual_info    1001         pfarm
         336       pmutual_info     501  pmutual_info    1001         pfarm
         720       pmutual_info     501  pmutual_info    1001         pfarm
ETTh2    96           iprollcov    1251      prollcov     501  pmutual_info
         192          iprollcov    1251      prollcov     501  pmutual_info
         336          iprollcov    1251      prollcov     501  pmutual_info
         720          iprollcov    1251      prollcov     501  pmutual_info
ETTm1    96              ipfarm    1251      prollcov    1501  pmutual_info
         192             ipfarm    1251      prollcov    1501  pmutual_info
         336             ipfarm    1251      prollcov    1501  pmutual_info
         720             ipfarm    1251      prollcov    1501  pmutual_info
ETTm2    96           iprollcov     751    iprollcorr     501     prollcorr
         192          iprollcov     751    iprollcorr     501     prollcorr
         336          iprollcov     751    iprollcorr     501     prollcorr
         720          iprollcov     751    iprollcorr     501     prollcorr
TrafficL 96               pfarm     751           NaN     NaN           NaN
         192                NaN     NaN           NaN     NaN           NaN
Weather  96           prollcorr    1001     iprollcov    1501    iprollcorr
         192          prollcorr    1001     iprollcov    1501    iprollcorr
         336          prollcorr    1001     iprollcov    1501    iprollcorr
         720          prollcorr    1001     iprollcov    1501    iprollcorr

Model                            TimeXer           iTransformer
Meta              pwindow   pconstructor pwindow   pconstructor pwindow
dataset  pred_len
ECL      96          1501         ipfarm     501   pmutual_info    1501
         192          NaN         ipfarm     501      prollcorr    1251
         336          NaN         ipfarm     501   pmutual_info    1501
         720          NaN         ipfarm     501   pmutual_info    1501
ETTh1    96          1001   pmutual_info     751   pmutual_info     751
         192         1001   pmutual_info     751   pmutual_info    1251
         336         1001   pmutual_info     751   pmutual_info    1251
         720         1001   pmutual_info     751   pmutual_info    1251
ETTh2    96          1501       prollcov     501      prollcorr    1251
         192         1501       prollcov     501      prollcorr    1501
         336         1501       prollcov     501      prollcorr    1501
         720         1501       prollcov     501      prollcorr    1501
ETTm1    96           501     iprollcorr     751  ipmutual_info    1501
         192          501     iprollcorr     751      ipentropy    1251
         336          501     iprollcorr     751  ipmutual_info    1501
         720          501     iprollcorr     751  ipmutual_info    1501
ETTm2    96          1001       pentropy    1251      iprollcov     751
         192         1001       pentropy    1251     iprollcorr    1501
         336         1001       pentropy    1251     iprollcorr    1501
         720         1001       pentropy    1251     iprollcorr    1501
TrafficL 96           NaN     iprollcorr     501     iprollcorr     501
         192          NaN            NaN     NaN     iprollcorr     501
Weather  96          1501  ipmutual_info     501  ipmutual_info    1251
         192         1501  ipmutual_info     501      prollcorr    1001
         336         1501  ipmutual_info     501  ipmutual_info    1251
         720         1501  ipmutual_info     501  ipmutual_info    1251

In [ ]:
latex_table_perf = perf_df.to_latex(multicolumn=True, multirow=True, longtable=False, escape=False)
latex_table_meta = meta_df.to_latex(multicolumn=True, multirow=True, longtable=False, escape=False)

from IPython.display import HTML

html = f"""
<textarea style="width:100%; height:400px;" readonly>{latex_table_meta}</textarea>
"""
display(HTML(html))

## Parameter behavior on accuracy when shaping

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    "ipentropy.csv",
    "prollcov.csv",
    "iprollcov.csv",
    "prollcorr.csv",
    "iprollcorr.csv",
    "pfarm.csv",
    "ipfarm.csv",
    "pmutual",
    "ipmutual",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    "iTransformer",
    # "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    "ETTh2",
    # "ETTm1",
    # "ETTm2",
    # "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

def count_good_results(x_array):
    return len([element for element in x_array if element > 0])

plot_results(
    tohist_df,
    value_col="pwindow",
    y_agg_col="improvement",
    agg_func=np.mean,
    group_col=[
        # "pwindow",
        "pconstructor",
        # "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    # smooth="kde",
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=0,
)

## Parameters effects on accuracy when shaping

In [ ]:
tohist_df = results_df

tohist_df = tohist_df[tohist_df["pconstructor"].isin([
    "pentropy.csv",
    # "ipentropy.csv",
    # "prollcov.csv",
    # "iprollcov.csv",
    # "prollcorr.csv",
    # "iprollcorr.csv",
    # "pfarm.csv",
    # "ipfarm.csv",
    # "pmutual",
    # "ipmutual",
])]

tohist_df = tohist_df[tohist_df["pred_len"].isin([
    96,
    # 192,
    # 336,
    # 720
])]

tohist_df = tohist_df[tohist_df["pwindow"].isin([
    501,
    751,
    1001,
    1251,
    1501
])]

tohist_df = tohist_df[tohist_df["model_name"].isin([
    # "iTransformer",
    "PatchTST",
    # "TimeXer",
    # "Crossformer",
    # "Autoformer"
])]

tohist_df = tohist_df[tohist_df["dataset"].isin([
    # "ETTh1",
    # "ETTh2",
    # "ETTm1",
    # "ETTm2",
    "Weather",
    # "ECL",
    # "Traffic"
])]

tohist_df.sort_values("improvement", ascending=False)

tohist_df["pwindow"] = pd.to_numeric(tohist_df["pwindow"])

plot_results(
    tohist_df,
    value_col="improvement",
    group_col=[
        "pwindow",
        # "pconstructor",
        "model_name",
        # "improvement",
        # "dataset",
    ],
    bins=30,
    smooth="interp",
    backend="plotly",
    vline_at_zero=True,
    vline_at_peak=True,
    min_peak_x=-100,
)

## Forecast plot

In [ ]:
pred_len = 96
# model_name = "TimeXer"
# dataset = "ETTh1"
model_name = "Crossformer"
dataset = "Weather"
cutoff_index = 2

forecast_plot_df = get_forecast_plot(
    model_name=model_name,
    dataset=dataset,
    pred_len=pred_len,
    cutoff_index=cutoff_index,
    best_results=best_results,
    all_results=all_results
)

forecast_plot_df.plot()

## Show the original and shaped data graphs

In [ ]:
from config_utils import datasets_path_mapping
from plotly_resampler import register_plotly_resampler
register_plotly_resampler(mode='auto')
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().set_output(transform="pandas")

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

dataset_path = datasets_path_mapping[dataset]

br = best_results[
    (best_results["model_name"] == model_name) & 
    (best_results["dataset"] == dataset) & 
    (best_results["pred_len"] == pred_len)
] # there should be only one with this filter
pwindow = br["pwindow"].values[0]
pconstructor = br["pconstructor"].values[0]
lookback_len = br["lookback_len"].values[0]

dataset_shaped_path = f"{dataset_path}{dataset}_w{pwindow}_{pconstructor}"
dataset_shaped = pd.read_csv(dataset_shaped_path)

max_index_to_plot = forecast_plot_df.index.values.max()
min_index_to_plot = forecast_plot_df.index.values.min()
time_index_to_separate = dataset_shaped.reset_index().iloc[min_index_to_plot]
print(f"Min: {min_index_to_plot} | Max: {max_index_to_plot}")

dataset_shaped = dataset_shaped # TODO: get the right index to plot
# dataset_shaped = dataset_shaped.iloc[min_index_to_plot-lookback_len:max_index_to_plot].set_index("date")
# fig = scaler.fit_transform(dataset_shaped).plot()

# fig.add_vline(x=time_index_to_separate["date"], line_dash="dash", line_color="green")

# fig.show()

dataset_shaped = dataset_shaped.set_index("date")
dataset_shaped.plot()

## Experimenting with forecast plot

In [ ]:

def get_forecast_plot_modified(model_name, dataset, pred_len, cutoff_index, best_results, all_results):

    exp_name = best_results[
        (best_results["model_name"] == model_name) & 
        (best_results["dataset"] == dataset) & 
        (best_results["pred_len"] == pred_len)
    ]["exp_name"].values[0] # there should be only one with this filter
    print(exp_name)

    metrics_shaped = pd.read_csv(f"./results/{exp_name}/_metrics.csv")
    print(f"Metrics shaped: {metrics_shaped}")


    pred_df = pd.read_csv(f"./results/{exp_name}/preds_vs_trues.csv")

    return pred_df

forecast_plot_df = get_forecast_plot_modified(
    model_name=model_name,
    dataset=dataset,
    pred_len=pred_len,
    cutoff_index=cutoff_index,
    best_results=best_results,
    all_results=all_results
)

forecast_plot_df