# Feature Ablation results
---

### Notes:

Experiments are run with the following datasets:

- ETTh1
- EPEX-DE
- Energy Load

And with the following models:

- MLP
- CNN
- LSTM (Lacks hyperparam tuning)

With prediction lengths of 96.

## Results tables
---

In [1]:
import os
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"
from results_utils_feature_ablation import get_results

In [2]:
all_results = get_results(results_directory="./results_feature_ablation/")
all_results.to_csv("results_mse_table_feature_ablation.csv")
all_results.sort_values(by="mse", ascending=True)

,mae,mse,rmse,mape,mspe,exp_name,model_name,features_powerset,pred_len,dataset
0,0.213695,0.077832,0.278983,0.161710,0.043907,long_term_forecast_96_96powerset_HUFL_LULL.csv...,MLP,"['HUFL', 'LULL']",96,ETTh1
0,0.222931,0.085324,0.292102,0.167048,0.046323,long_term_forecast_96_96powerset_MUFL_LULL.csv...,MLP,"['MUFL', 'LULL']",96,ETTh1
0,0.223418,0.087211,0.295314,0.162883,0.043452,long_term_forecast_96_96powerset_empty.csv_MLP...,MLP,['empty'],96,ETTh1
0,0.225497,0.089161,0.298599,0.165280,0.045330,long_term_forecast_96_96powerset_LULL.csv_MLP_...,MLP,['LULL'],96,ETTh1
0,0.235362,0.093912,0.306451,0.175936,0.049837,long_term_forecast_96_96powerset_HUFL_MUFL_LUL...,MLP,"['HUFL', 'MUFL', 'LULL']",96,ETTh1
...,...,...,...,...,...,...,...,...,...,...
0,1.172957,1.648785,1.284050,0.857156,0.879671,long_term_forecast_720_96powerset_HUFL_MUFL_MU...,Transformer,"['HUFL', 'MUFL', 'MULL', 'LUFL', 'LULL']",720,ETTh1
0,1.160703,1.654707,1.286354,0.854785,0.858200,long_term_forecast_192_96powerset_HULL_LUFL_LU...,Transformer,"['HULL', 'LUFL', 'LULL']",192,ETTh1
0,1.168606,1.845743,1.358581,0.857744,0.929646,long_term_forecast_96_96powerset_HULL_MUFL_MUL...,Transformer,"['HULL', 'MUFL', 'MULL', 'LUFL', 'LULL']",96,ETTh1
0,1.224022,1.902089,1.379162,0.878301,0.959561,long_term_forecast_720_96powerset_HULL_MUFL_MU...,Transformer,"['HULL', 'MUFL', 'MULL', 'LULL']",720,ETTh1
0,1.278340,2.117658,1.455217,0.945814,1.092593,long_term_forecast_96_96powerset_HUFL_HULL_MUF...,Transformer,"['HUFL', 'HULL', 'MUFL', 'LUFL', 'LULL']",96,ETTh1

In [3]:
all_results[all_results["model_name"] == "LSTM"]

,mae,mse,rmse,mape,mspe,exp_name,model_name,features_powerset,pred_len,dataset
0,0.293340,0.129376,0.359689,0.232540,0.098019,long_term_forecast_96_96powerset_LUFL_LULL.csv...,LSTM,"['LUFL', 'LULL']",96,ETTh1
0,0.303876,0.138775,0.372525,0.218061,0.066686,long_term_forecast_96_96powerset_LUFL.csv_LSTM...,LSTM,['LUFL'],96,ETTh1
0,0.323371,0.161075,0.401341,0.241494,0.090791,long_term_forecast_96_96powerset_MUFL_LULL.csv...,LSTM,"['MUFL', 'LULL']",96,ETTh1
0,0.323538,0.161895,0.402361,0.232606,0.078518,long_term_forecast_96_96powerset_MUFL_LUFL_LUL...,LSTM,"['MUFL', 'LUFL', 'LULL']",96,ETTh1
0,0.339020,0.168776,0.410823,0.242174,0.081726,long_term_forecast_96_96powerset_HUFL_MUFL_LUL...,LSTM,"['HUFL', 'MUFL', 'LULL']",96,ETTh1
...,...,...,...,...,...,...,...,...,...,...
0,0.547188,0.944054,0.971624,2.270848,452.755430,long_term_forecast_192_96powerset_empty.csv_LS...,LSTM,['empty'],192,Energy
0,0.902933,0.950794,0.975087,0.675262,0.527854,long_term_forecast_336_96powerset_HUFL_HULL_LU...,LSTM,"['HUFL', 'HULL', 'LULL']",336,ETTh1
0,0.927588,0.962263,0.980950,0.685045,0.505046,long_term_forecast_336_96powerset_HUFL_HULL_MU...,LSTM,"['HUFL', 'HULL', 'MUFL', 'LUFL']",336,ETTh1
0,0.930403,0.963428,0.981544,0.694439,0.513250,long_term_forecast_192_96powerset_HUFL_HULL_MU...,LSTM,"['HUFL', 'HULL', 'MUFL', 'MULL']",192,ETTh1
0,0.948758,1.039252,1.019437,0.719400,0.590787,long_term_forecast_192_96powerset_HUFL_HULL_LU...,LSTM,"['HUFL', 'HULL', 'LUFL', 'LULL']",192,ETTh1

In [4]:
all_results.groupby([
    # "dataset",
    "model_name",
    # "pred_len"
]).size()

model_name
CNN            400
LSTM           268
MLP            400
Transformer    400
dtype: int64

## Plotting results
---

In [5]:
import os
import numpy as np
import pandas as pd
pd.options.plotting.backend = "plotly"
from plotly_resampler import register_plotly_resampler
register_plotly_resampler(mode='auto')

from results_utils_feature_ablation import get_forecast_plot

root_directory = "/home/ubuntu/repos/TSPindorama/results_feature_ablation/"

/home/ubuntu/master_realm/lib/python3.12/site-packages/dash/_jupyter.py:30: DeprecationWarning: The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.
  _dash_comm = Comm(target_name="dash")

In [6]:
dataset_name = "ETTh1"
model = "LSTM"
features_of_interest = ['empty']
pred_len = 96
df_plot = get_forecast_plot(
    dataset_name=dataset_name,
    model=model,
    pred_len=pred_len,
    features_of_interest=features_of_interest,
    root_directory=root_directory,
    offset_idx=0
)

df_plot.plot(title=f"Forecast Plot for {dataset_name} - Model {model} - Features: {', '.join(features_of_interest)}",)

FigureWidgetResampler({
    'data': [{'hovertemplate': 'variable=true<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'true',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'true',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'a1489af8-72d9-43c0-b027-c26e396b941c',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95]),
              'xaxis': 'x',
              'y': array([-0.8623407 , -0.86996883, -0.83161   , -0.8775971 , -0.915956  ,
                          -0.8929624 , -0.9005906 , -0.9005906 , -0.8393472 , -0.8393472 ,
                          -0.80861646, -0.7932511 , -0.77025753, -0.5939374 , -0.5403222 ,
                          -0.6476616 , -0.66302705, -0.60167456, -0.67065525, -0.6246682 ,
                          -0.68602055, -0.68602055, -0.7396359 , -0.8546035 , -0.86996883,
                          -0.9543148 , -0.9313213 , -0.98493654, -1.0232955 , -1.0155584 ,
                          -1.0539172 , -1.0692825 , -1.0539172 , -1.0309236 , -0.8623407 ,
                          -0.8929624 , -0.8623407 , -0.7090141 , -0.6476616 , -0.6399246 ,
                          -0.6322963 , -0.5709439 , -0.6476616 , -0.7090141 , -0.7396359 ,
                          -0.80098826, -0.80861646, -0.80098826, -0.82398176, -0.8393472 ,
                          -0.82398176, -0.90832776, -0.8393472 , -0.77025753, -0.6936488 ,
                          -0.7320076 , -0.6782834 , -0.5939374 , -0.6093028 , -0.61693096,
                          -0.50196326, -0.40998912, -0.37163022, -0.49433511, -0.41761738,
                          -0.46360445, -0.58630925, -0.60167456, -0.72427046, -0.77025753,
                          -0.80098826, -0.80098826, -0.82398176, -0.77025753, -0.7932511 ,
                          -0.6552899 , -0.6246682 , -0.67065525, -0.6782834 , -0.67065525,
                          -0.56331575, -0.49433511, -0.47134152, -0.5097004 , -0.46360445,
                          -0.30264965, -0.25666258, -0.37936738, -0.44061086, -0.53269404,
                          -0.5709439 , -0.5786811 , -0.5939374 , -0.5709439 , -0.6322963 ,
                          -0.67065525], dtype=float32),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=pred<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'pred',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'pred',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'b000e81b-9351-4b00-b29f-6bae77d896e1',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95]),
              'xaxis': 'x',
              'y': array([-0.8381986 , -0.8561905 , -0.8532152 , -0.83205485, -0.82829857,
                          -0.84168476, -0.8298838 , -0.82580733, -0.8234627 , -0.8062994 ,
                          -0.79303896, -0.77318406, -0.7635526 , -0.76119083, -0.75555044,
                          -0.74411595, -0.7467976 , -0.7359701 , -0.7260539 , -0.72910607,
                          -0.72693664, -0.7437045 , -0.7306201 , -0.75226885, -0.74296826,
                          -0.75344706, -0.76192236, -0.7553637 , -0.7643364 , -0.76086026,
                          -0.756514  , -0.7389877 , -0.74583703, -0.7392366 , -0.7319276 ,
                          -0.7405765 , -0.7348892 , -0.7148446 , -0.7111114 , -0.7027927 ,
                          -0.7174995 , -0.700223  , -0.7108781 , -0.71967715, -0.7180141 ,
                          -0.71211296, -0.72351885, -0.72070706, -0.7285493 , -0.7226954 ,
                          -0.7214661 , -0.7528928 , -0.72853315, -0.73794156, -0.72655606,
                          -0.7203887 , -0.7250433 , -0.72282124, -0.72145116, -0.70619047,
                          -0.69103295, -0.7018381 , -0.7168849 , -0.697087  , -0.69769835,
                          -0.6998357 , -0.69485   , -0.6891011 , -0.72779393, -0.7350225 ,
                          -0.7297809 , -0.7374904 , -0.7392038 , -0.75667876, -0.74980277,
                          -0.74723196, -0.7476194 , -0.76556826, -0.7605739 , -0.7649057 ,
                          -0.7688335 , -0.75009316, -0.7472833 , -0.73651356, -0.71959794,
                          -0.7371191 , -0.71710974, -0.7100983 , -0.7303487 , -0.7255013 ,
                          -0.7468911 , -0.7294755 , -0.72542465, -0.7194489 , -0.73860455,
                          -0.7559138 ], dtype=float32),
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Forecast Plot for ETTh1 - Model LSTM - Features: empty'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [7]:
dataset_name = "ETTh1"
model = "LSTM"
features_of_interest = ['LUFL', 'LULL']	
pred_len = 96

df_plot = get_forecast_plot(
    dataset_name=dataset_name,
    model=model,
    pred_len=pred_len,
    features_of_interest=features_of_interest,
    root_directory=root_directory,
    offset_idx=0
)

df_plot.plot(title=f"Forecast Plot for {dataset_name} - Model {model} - Features: {', '.join(features_of_interest)}",)

FigureWidgetResampler({
    'data': [{'hovertemplate': 'variable=true<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'true',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'true',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'c97a5922-2842-4ed2-b701-2cf3eb24ed3a',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95]),
              'xaxis': 'x',
              'y': array([-0.8623407 , -0.86996883, -0.83161   , -0.8775971 , -0.915956  ,
                          -0.8929624 , -0.9005906 , -0.9005906 , -0.8393472 , -0.8393472 ,
                          -0.80861646, -0.7932511 , -0.77025753, -0.5939374 , -0.5403222 ,
                          -0.6476616 , -0.66302705, -0.60167456, -0.67065525, -0.6246682 ,
                          -0.68602055, -0.68602055, -0.7396359 , -0.8546035 , -0.86996883,
                          -0.9543148 , -0.9313213 , -0.98493654, -1.0232955 , -1.0155584 ,
                          -1.0539172 , -1.0692825 , -1.0539172 , -1.0309236 , -0.8623407 ,
                          -0.8929624 , -0.8623407 , -0.7090141 , -0.6476616 , -0.6399246 ,
                          -0.6322963 , -0.5709439 , -0.6476616 , -0.7090141 , -0.7396359 ,
                          -0.80098826, -0.80861646, -0.80098826, -0.82398176, -0.8393472 ,
                          -0.82398176, -0.90832776, -0.8393472 , -0.77025753, -0.6936488 ,
                          -0.7320076 , -0.6782834 , -0.5939374 , -0.6093028 , -0.61693096,
                          -0.50196326, -0.40998912, -0.37163022, -0.49433511, -0.41761738,
                          -0.46360445, -0.58630925, -0.60167456, -0.72427046, -0.77025753,
                          -0.80098826, -0.80098826, -0.82398176, -0.77025753, -0.7932511 ,
                          -0.6552899 , -0.6246682 , -0.67065525, -0.6782834 , -0.67065525,
                          -0.56331575, -0.49433511, -0.47134152, -0.5097004 , -0.46360445,
                          -0.30264965, -0.25666258, -0.37936738, -0.44061086, -0.53269404,
                          -0.5709439 , -0.5786811 , -0.5939374 , -0.5709439 , -0.6322963 ,
                          -0.67065525], dtype=float32),
              'yaxis': 'y'},
             {'hovertemplate': 'variable=pred<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'pred',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'pred',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'uid': 'eea5a45a-05d2-4164-bdf2-7ba8fef19675',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95]),
              'xaxis': 'x',
              'y': array([-1.2501359 , -1.236481  , -1.2370269 , -1.2212629 , -1.2459129 ,
                          -1.2162592 , -1.285282  , -1.2406844 , -1.2516028 , -1.2760655 ,
                          -1.269668  , -1.2755322 , -1.2460568 , -1.2197325 , -1.1870501 ,
                          -1.1661862 , -1.1561692 , -1.1380283 , -1.1226457 , -1.1367648 ,
                          -1.1144382 , -1.0880095 , -1.1673611 , -1.1487023 , -1.1177498 ,
                          -1.087518  , -1.1224148 , -1.1430429 , -1.0871922 , -1.1075099 ,
                          -1.0827485 , -1.0855671 , -1.1347846 , -1.1185187 , -1.1165874 ,
                          -1.1537532 , -1.1281588 , -1.1378886 , -1.0850564 , -1.094818  ,
                          -1.0753483 , -1.0578058 , -0.977324  , -1.0487951 , -0.9643598 ,
                          -0.94696933, -0.91659445, -0.9382599 , -0.93533224, -0.88962156,
                          -0.85590535, -0.8774033 , -0.857595  , -0.900556  , -0.8521211 ,
                          -0.87800413, -0.8232    , -0.8321475 , -0.8432744 , -0.86766875,
                          -0.86800367, -0.840564  , -0.8705749 , -0.84938484, -0.8553677 ,
                          -0.8576197 , -0.83963406, -0.8459641 , -0.8653976 , -0.7993419 ,
                          -0.80581915, -0.77518845, -0.79740566, -0.7449227 , -0.81121665,
                          -0.8074559 , -0.8301159 , -0.84366274, -0.8608048 , -0.90209764,
                          -0.8674966 , -0.87849796, -0.9234849 , -0.92934203, -0.88099104,
                          -0.93253976, -0.9350642 , -0.9167104 , -0.92349416, -0.9264746 ,
                          -0.9075091 , -0.86610377, -0.87134606, -0.8932436 , -0.8854967 ,
                          -0.8958961 ], dtype=float32),
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Forecast Plot for ETTh1 - Model LSTM - Features: LUFL, LULL'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})